version: '3.8'

services:

  backend:
    build:
      context: backend
      target: production

  frontend:
    build:
      context: frontend
      target: production

  proxy:
    build:
      context: nginx
    ports:
      - '1234:80'
    logging:
      driver: none

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: none

volumes:
  postgres:
    driver: local